input {
  tcp {
    port => 5044
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "flask-app-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "123456"
    ssl_enabled => true
    ssl_certificate_verification => false
  }
}