CREATE DATABASE [OurFirstDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OurFirstDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\OurFirstDatabase.mdf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OurFirstDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\OurFirstDatabase_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [OurFirstDatabase] SET COMPATIBILITY_LEVEL = 170
GO
ALTER DATABASE [OurFirstDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [OurFirstDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OurFirstDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OurFirstDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OurFirstDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OurFirstDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET  READ_WRITE 
GO
ALTER DATABASE [OurFirstDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OurFirstDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [OurFirstDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OurFirstDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OurFirstDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OurFirstDatabase] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [OurFirstDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
USE [OurFirstDatabase]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [OurFirstDatabase] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
