name: SQL Deployment Pipeline


on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Run SQL script
        run: sqlcmd -i cicd-project/sql/deploy.sql
        
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SQLCMD
        run: |
          choco install sqlcmd -y

      - name: Run Deployment Script
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          sqlcmd -S $env:SQL_SERVER `
                 -d $env:SQL_DATABASE `
                 -U $env:SQL_USER `
                 -P $env:SQL_PASSWORD `
                 -i sql/deploy.sql