name: GitHub-MS Teams Events Integration
 
on:
  push:
  pull_request:
  create:
 
jobs:
  notify-teams:
    runs-on: ubuntu-latest
 
    steps:
      - name: Send message to MS Teams
        run: |
          EVENT_NAME="${{ github.event_name }}"
 
          if [ "$EVENT_NAME" = "push" ]; then
            MESSAGE="🚀 Push event in ${{ github.repository }} by ${{ github.actor }}.\n\nCommit: ${{ github.event.head_commit.message }}\n🔗 ${{ github.event.head_commit.url }}"
         
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            MESSAGE="📌 Pull Request event in ${{ github.repository }} by ${{ github.actor }}.\n\nTitle: ${{ github.event.pull_request.title }}\n🔗 ${{ github.event.pull_request.html_url }}"
         
          else
            MESSAGE="📦 Create event in ${{ github.repository }} by ${{ github.actor }}.\nRef: ${{ github.ref }}"
          fi
 
          curl -H "Content-Type: application/json" \
          -d "{\"text\": \"$MESSAGE\"}" \
          ${{ secrets.TEAMS_WEBHOOK }}