name: SQL Deployment Pipeline

on:
  push:

jobs:

  dev-test:
    runs-on: windows-latest

    steps:
      - name: Dev Notify
        shell: pwsh
        run: |
          $body = @{
            text = "DEV STARTED`nRepo: ${{ github.repository }}"
          }

          Invoke-RestMethod -Method Post `
            -Uri "${{ secrets.TEAMS_WEBHOOK }}" `
            -Body ($body | ConvertTo-Json) `
            -ContentType "application/json"

  dev-deploy:
    needs: dev-test
    uses: ./.github/workflows/sql-template.yml

    with:
      target_env: production

    secrets: inherit


  production:
    needs: dev-deploy
    runs-on: windows-latest

    steps:
      - name: Prod Notify
        shell: pwsh
        run: |
          $body = @{
            text = "PROD STARTED`nRepo: ${{ github.repository }}"
          }

          Invoke-RestMethod -Method Post `
            -Uri "${{ secrets.TEAMS_WEBHOOK }}" `
            -Body ($body | ConvertTo-Json) `
            -ContentType "application/json"

  prod-deploy:
    needs: production
    uses: ./.github/workflows/sql-template.yml

    with:
      target_env: partner-production

    secrets: inherit