name: SQL Deployment Template

on:
  workflow_call:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SQLCMD
        run: choco install sqlcmd -y

      - name: Run SQL Script
        shell: pwsh
        run: |
          sqlcmd -S "${{ secrets.SQL_SERVER }}" `
                 -d "${{ secrets.SQL_DATABASE }}" `
                 -U "${{ secrets.SQL_USER }}" `
                 -P "${{ secrets.SQL_PASSWORD }}" `
                 -i "cicd-project/sql/deploy.sql"